name: mason_custom_lints
description: A package to add custom lints to your project.
version: 1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analyzer: 5.3.1
  analyzer_plugin: 0.11.2
  custom_lint_builder: 0.0.15

dev_dependencies:
  lints: 2.0.0
