name: my_dart_app
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dev_dependencies:
  custom_lint: 0.1.0
  mason_custom_lints:
    path: ../mason_custom_lints
